spring:
  application:
    name: api-gateway

  ##GATEWAY CONFIGURATIONS
  cloud:
    gateway:
      routes:
        ## service1
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/auth/**


        ## Service2
        - id: book-service
          uri: lb://BOOK-SERVICE
          predicates:
            - Path=/book/**,/flight/**,/scheduledFlight/**
          filters:
            - AuthenticationFilter
            - name: CircuitBreaker
              args:
                  name: book-service
                  fallbackUri: forward:/fallback/book-service



        ## Service3
        - id: flight-service
          uri: lb://FLIGHT-SERVICE
          predicates:
            - Path=/flight/**,/scheduledFlight/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health

  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      book-service:
        registerHealthIndicator: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED